/****** Object:  Table [dbo].[HISTORICO_TRANSACAO]    Script Date: 17/01/2023 09:20:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HISTORICO_TRANSACAO](
	[NF_ENTRADA] [varchar](10) NOT NULL,
	[SERIE_NF_ENTRADA] [varchar](2) NOT NULL,
	[FORNECEDOR] [varchar](50) NOT NULL,
	[DATA] [datetime] NULL,
	[USUARIO] [varchar](50) NOT NULL,
	[OPERACAO] [varchar](1) NOT NULL,
 CONSTRAINT [PK_HISTORICO_TRANSACAO] PRIMARY KEY CLUSTERED 
(
	[NF_ENTRADA] ASC,
	[SERIE_NF_ENTRADA] ASC,
	[FORNECEDOR] ASC,
	[USUARIO] ASC,
	[OPERACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


