/****** Object:  Table [dbo].[USUARIOS]    Script Date: 16/01/2023 09:40:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USUARIOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO] [varchar](50) NULL,
	[PAPEL] [varchar](1) NULL,
	[VALOR_MINIMO] [numeric](14, 2) NULL,
	[VALOR_MAXIMO] [numeric](14, 2) NULL,
	[SENHA] [varbinary](100) NULL,
 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


INSERT INTO USUARIOS
(
USUARIO,
PAPEL,
VALOR_MINIMO,
VALOR_MAXIMO,
SENHA
)
VALUES 
(
'JOAO',
'V',
0,
1000,
CONVERT(varbinary(100), PWDENCRYPT('teste'))
)
